export const reviewList = [
  {
    videoUrl:
      'https://ap.education/static/video/reviews/fullReviews/fullReview1.mp4',
  },
  {
    videoUrl:
      'https://ap.education/static/video/reviews/fullReviews/fullReview2.mp4',
  },
  {
    videoUrl:
      'https://ap.education/static/video/reviews/fullReviews/fullReview3.mp4',
  },
  {
    videoUrl:
      'https://ap.education/static/video/reviews/fullReviews/fullReview4.mp4',
  },
  {
    videoUrl:
      'https://ap.education/static/video/reviews/fullReviews/fullReview5.mp4',
  },
  {
    videoUrl:
      'https://ap.education/static/video/reviews/fullReviews/fullReview6.mp4',
  },
  {
    videoUrl:
      'https://ap.education/static/video/reviews/fullReviews/fullReview7.mp4',
  },
  {
    videoUrl:
      'https://ap.education/static/video/reviews/fullReviews/fullReview8.mp4',
  },
  {
    videoUrl:
      'https://ap.education/static/video/reviews/fullReviews/fullReview9.mp4',
  },
  {
    videoUrl:
      'https://ap.education/static/video/reviews/fullReviews/fullReview10.mp4',
  },
];
