export const reviewList = [
    {
      videoUrl:
        'https://ap.education/static/video/reviews/fullReviews/fullReview1.webm',
    },
    {
      videoUrl:
        'https://ap.education/static/video/reviews/fullReviews/fullReview2.webm',
    },
    {
      videoUrl:
        'https://ap.education/static/video/reviews/fullReviews/fullReview3.webm',
    },
    {
      videoUrl:
        'https://ap.education/static/video/reviews/fullReviews/fullReview4.webm',
    },
    {
      videoUrl:
        'https://ap.education/static/video/reviews/fullReviews/fullReview5.webm',
    },
    {
      videoUrl:
        'https://ap.education/static/video/reviews/fullReviews/fullReview6.webm',
    },
    {
      videoUrl:
        'https://ap.education/static/video/reviews/fullReviews/fullReview7.webm',
    },
    {
      videoUrl:
        'https://ap.education/static/video/reviews/fullReviews/fullReview8.webm',
    },
    {
      videoUrl:
        'https://ap.education/static/video/reviews/fullReviews/fullReview9.webm',
    },
    {
      videoUrl:
        'https://ap.education/static/video/reviews/fullReviews/fullReview10.webm',
    },
  ];